app/controllers/accounts.py
import decimal
from collections.abc import Iterable

import sqlalchemy as sa
from flask import Blueprint, render_template
from flask_wtf import FlaskForm
from wtforms import (
    SelectField,
    StringField,
)
from wtforms.validators import DataRequired

from app.extensions import db
from app.models.ledger import LedgerAccount
from app.utils import htmx_only

blueprint = Blueprint("accounts", __name__)


class AddLedgerAccountForm(FlaskForm):
    account_name = StringField("Account", validators=[DataRequired()])
    account_label = StringField("Label", validators=[DataRequired()])
    account_class = SelectField(
        "Class",
        choices=[
            ("BALANCE_SHEET", "Balance Sheet (1)"),
            ("INCOME_STATEMENT", "Income Statement (2)"),
        ],
        validators=[DataRequired()],
    )
    account_type = SelectField(
        "Type",
        choices=[
            ("ASSET", "Asset (1)"),
            ("LIABILITY", "Liability (2)"),
            ("EQUITY", "Equity (3)"),
            ("REVENUE", "Revenue (4)"),
            ("EXPENSE", "Expense (5)"),
        ],
        validators=[DataRequired()],
    )


@blueprint.route("/", methods=["GET"])
def index():
    form = AddLedgerAccountForm()
    accounts = db.session.scalars(
        sa.select(LedgerAccount).order_by(LedgerAccount.account_name)
    ).all()
    return render_template("accounts/index.html", accounts=accounts, form=form)


@blueprint.route("/taccounts", methods=["GET"])
def taccounts():
    def _calculate_balance(accounts: Iterable[LedgerAccount]):
        return sum(
            [account.account_balance for account in accounts],
            start=decimal.Decimal("0"),
        )

    asset_accounts = db.session.scalars(
        sa.select(LedgerAccount)
        .order_by(LedgerAccount.account_name)
        .where(LedgerAccount.account_type == LedgerAccount.AccountType.ASSET)
    ).all()
    asset_balance = _calculate_balance(asset_accounts)
    liability_accounts = db.session.scalars(
        sa.select(LedgerAccount)
        .order_by(LedgerAccount.account_name)
        .where(
            sa.or_(
                LedgerAccount.account_type == LedgerAccount.AccountType.LIABILITY,
                LedgerAccount.account_type == LedgerAccount.AccountType.EQUITY,
            )
        )
    ).all()
    liability_balance = _calculate_balance(liability_accounts)
    expense_accounts = db.session.scalars(
        sa.select(LedgerAccount)
        .order_by(LedgerAccount.account_name)
        .where(LedgerAccount.account_type == LedgerAccount.AccountType.EXPENSE)
    ).all()
    expense_balance = _calculate_balance(expense_accounts)
    revenue_accounts = db.session.scalars(
        sa.select(LedgerAccount)
        .order_by(LedgerAccount.account_name)
        .where(LedgerAccount.account_type == LedgerAccount.AccountType.REVENUE)
    ).all()
    revenue_balance = _calculate_balance(revenue_accounts)
    return render_template(
        "accounts/taccounts.html",
        asset_accounts=asset_accounts,
        asset_balance=asset_balance,
        liability_accounts=liability_accounts,
        liability_balance=liability_balance,
        expense_accounts=expense_accounts,
        expense_balance=expense_balance,
        revenue_accounts=revenue_accounts,
        revenue_balance=revenue_balance,
    )


# HTMX Only Views
@blueprint.route("/_/account", methods=["POST"])
@htmx_only
def htmx_add_account():
    # TODO: Handle errors
    form = AddLedgerAccountForm()
    if form.validate_on_submit():
        account = LedgerAccount(
            account_name=form.account_name.data,
            account_label=form.account_label.data,
            account_class={
                "BALANCE_SHEET": LedgerAccount.AccountClass.BALANCE_SHEET,
                "INCOME_STATEMENT": LedgerAccount.AccountClass.INCOME_STATEMENT,
            }[form.account_class.data],
            account_type={
                "ASSET": LedgerAccount.AccountType.ASSET,
                "LIABILITY": LedgerAccount.AccountType.LIABILITY,
                "EQUITY": LedgerAccount.AccountType.EQUITY,
                "REVENUE": LedgerAccount.AccountType.REVENUE,
                "EXPENSE": LedgerAccount.AccountType.EXPENSE,
            }[form.account_type.data],
        )
        db.session.add(account)
        db.session.commit()

    accounts = db.session.scalars(
        sa.select(LedgerAccount).order_by(LedgerAccount.account_name)
    ).all()
    return render_template("accounts/partials/account-list.html", accounts=accounts)

app/templates/accounts/index.html
{% extends 'layouts/base.html' %}
{% block content %}
    <div class="w-full flex-1 min-h-0 p-2 grid grid-cols-5 gap-x-4">
        <div class="col-span-3 overflow-y-scroll">
            {{ render_partial("accounts/partials/account-list.html", accounts=accounts) }}
        </div>
        <div class="col-span-2 flex flex-col min-h-0">
            <form hx-post="{{ url_for("accounts.htmx_add_account") }}"
                  hx-target="#account-list"
                  hx-swap="outerHTML"
                  class="flex-1 flex flex-col min-h-0">
                {{ form.hidden_tag() }}
                <div class="flex-1 min-h-0 overflow-y-scroll">
                    <div class="grid grid-cols-6 gap-x-2 gap-y-2">
                        <div class="col-span-6">
                            {{ form.account_name.label(class="block text-sm font-medium leading-6 text-gray-900") }}
                            <div class="mt-2">
                                {{ form.account_name(class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1
                                                                ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset
                                                                focus:ring-indigo-600 sm:text-sm sm:leading-6") }}
                            </div>
                        </div>
                        <div class="col-span-6">
                            {{ form.account_label.label(class="block text-sm font-medium leading-6 text-gray-900") }}
                            <div class="mt-2">
                                {{ form.account_label(class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1
                                                                ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset
                                                                focus:ring-indigo-600 sm:text-sm sm:leading-6") }}
                            </div>
                        </div>
                        <div class="col-span-6">
                            {{ form.account_class.label(class="block text-sm font-medium leading-6 text-gray-900") }}
                            <div class="mt-2">
                                {{ form.account_class(class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset
                                                                ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6") }}
                            </div>
                        </div>
                        <div class="col-span-6">
                            {{ form.account_type.label(class="block text-sm font-medium leading-6 text-gray-900") }}
                            <div class="mt-2">
                                {{ form.account_type(class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset
                                                                ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6") }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mt-2 flex-none">
                    <button type="submit"
                            class="w-full rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                        Add
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/accounts/taccounts.html
{% extends 'layouts/base.html' %}
{% block content %}
    <div class="w-full flex-1 min-h-0 p-2 grid grid-cols-4 overflow-y-auto">
        <div class="col-span-1 flex flex-col p-1">
            <div class="flex flex-col flex-none border-2">
                <p class="font-bold text-center">Assets</p>
                <span class="text-center">Balance: {{ '%0.2f'|format(asset_balance|float) }}</span>
            </div>
            <div class="mt-2 flex flex-col min-h-0 overflow-y-auto border-2 gap-y-4">
                {% for account in asset_accounts %}
                    {{ render_partial("accounts/partials/taccount.html", account=account) }}
                {% endfor %}
            </div>
        </div>
        <div class="col-span-1 flex flex-col p-1">
            <div class="flex flex-col flex-none border-2">
                <p class="font-bold text-center">Liability</p>
                <span class="text-center">Balance: {{ '%0.2f'|format(liability_balance|float) }}</span>
            </div>
            <div class="mt-2 flex flex-col min-h-0 overflow-y-auto border-2 gap-y-4">
                {% for account in liability_accounts %}
                    {{ render_partial("accounts/partials/taccount.html", account=account) }}
                {% endfor %}
            </div>
        </div>
        <div class="col-span-1 flex flex-col p-1">
            <div class="flex flex-col flex-none border-2">
                <p class="font-bold text-center">Expense</p>
                <span class="text-center">Balance: {{ '%0.2f'|format(expense_balance|float) }}</span>
            </div>
            <div class="mt-2 flex flex-col min-h-0 overflow-y-auto border-2 gap-y-4">
                {% for account in expense_accounts %}
                    {{ render_partial("accounts/partials/taccount.html", account=account) }}
                {% endfor %}
            </div>
        </div>
        <div class="col-span-1 flex flex-col p-1">
            <div class="flex flex-col flex-none border-2">
                <p class="font-bold text-center">Revenue</p>
                <span class="text-center">Balance: {{ '%0.2f'|format(revenue_balance|float) }}</span>
            </div>
            <div class="mt-2 flex flex-col min-h-0 overflow-y-auto border-2 gap-y-4">
                {% for account in revenue_accounts %}
                    {{ render_partial("accounts/partials/taccount.html", account=account) }}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}