app/models/ledger.py
import decimal
import enum

from sqlalchemy import ForeignKeyConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base
from app.models.types import datetime_tz, intpk


class LedgerAccount(Base):
    __tablename__ = "ledger_account"

    class AccountClass(enum.Enum):
        BALANCE_SHEET = 1
        INCOME_STATEMENT = 2

        def __str__(self) -> str:
            return {
                self.BALANCE_SHEET: "Balance Sheet",
                self.INCOME_STATEMENT: "Income Statement",
            }[self]

    class AccountType(enum.Enum):
        ASSET = 1
        LIABILITY = 2
        EQUITY = 3
        REVENUE = 4
        EXPENSE = 5

        def __str__(self) -> str:
            return {
                self.ASSET: "Asset",
                self.LIABILITY: "Liability",
                self.EQUITY: "Equity",
                self.REVENUE: "Revenue",
                self.EXPENSE: "Expense",
            }[self]

    class AccountBalanceType(enum.Enum):
        DEBIT_BALANCE = 1
        CREDIT_BALANCE = 2

        def __str__(self) -> str:
            return {
                self.DEBIT_BALANCE: "Debit Balance",
                self.CREDIT_BALANCE: "Credit Balance",
            }[self]

    # Columns
    account_id: Mapped[intpk]
    account_name: Mapped[str] = mapped_column(unique=True)
    account_label: Mapped[str]
    account_class: Mapped[AccountClass]
    account_type: Mapped[AccountType]

    # Relationships
    items: Mapped[list["LedgerEntryItem"]] = relationship(back_populates="account")

    @property
    def account_balance_type(self) -> AccountBalanceType:
        if self.account_type in [self.AccountType.ASSET, self.AccountType.EXPENSE]:
            return self.AccountBalanceType.DEBIT_BALANCE
        return self.AccountBalanceType.CREDIT_BALANCE

    @property
    def account_balance(self) -> decimal.Decimal:
        total_debit = sum(
            [
                item.amount
                for item in self.items
                if item.type == LedgerEntryItem.Type.DEBIT
            ],
            start=decimal.Decimal("0"),
        )
        total_credit = sum(
            [
                item.amount
                for item in self.items
                if item.type == LedgerEntryItem.Type.CREDIT
            ],
            start=decimal.Decimal("0"),
        )

        if self.account_balance_type == LedgerAccount.AccountBalanceType.DEBIT_BALANCE:
            return total_debit - total_credit
        return total_credit - total_debit


class LedgerEntry(Base):
    __tablename__ = "ledger_entry"

    # Columns
    id: Mapped[intpk]
    date: Mapped[datetime_tz]

    # Relationships
    items: Mapped[list["LedgerEntryItem"]] = relationship(back_populates="entry")


class LedgerEntryItem(Base):
    __tablename__ = "ledger_entry_item"
    __table_args__ = (
        ForeignKeyConstraint(["account_id"], [LedgerAccount.account_id]),
        ForeignKeyConstraint(["entry_id"], [LedgerEntry.id]),
    )

    class Type(enum.Enum):
        DEBIT = "D"
        CREDIT = "C"

    # Columns
    id: Mapped[intpk]
    date: Mapped[datetime_tz]
    account_id: Mapped[int]
    type: Mapped[Type]
    amount: Mapped[decimal.Decimal]
    entry_id: Mapped[int]

    # Relationshipts
    account: Mapped[LedgerAccount] = relationship(back_populates="items")
    entry: Mapped[LedgerEntry] = relationship(back_populates="items")

    @property
    def is_debit(self) -> bool:
        return self.type == self.Type.DEBIT

    @property
    def is_credit(self) -> bool:
        return self.type == self.Type.CREDIT

app/controllers/ledger.py
import datetime as dt

import sqlalchemy as sa
from flask import Blueprint, abort, render_template
from flask_wtf import FlaskForm
from wtforms import (
    DateField,
    DecimalField,
    FieldList,
    Form,
    FormField,
    SelectField,
    StringField,
)
from wtforms.validators import DataRequired

from app.extensions import db
from app.models.ledger import LedgerAccount, LedgerEntry
from app.services.ledger import LedgerEntryBuilder
from app.utils import htmx_only

blueprint = Blueprint("ledger", __name__)


class AddLedgerEntryItemForm(Form):
    type_ = SelectField(
        "Type", choices=[("D", "Debit"), ("C", "Credit")], validators=[DataRequired()]
    )
    account = SelectField("Account", validators=[DataRequired()])
    amount = DecimalField("Amount", validators=[DataRequired()])


class AddLedgerEntryForm(FlaskForm):
    date = DateField("Date", validators=[DataRequired()])
    description = StringField("Description", validators=[DataRequired()])
    items = FieldList(FormField(AddLedgerEntryItemForm))


def _prepare_form(form: AddLedgerEntryForm):
    accounts = db.session.scalars(
        sa.select(LedgerAccount).order_by(LedgerAccount.account_name)
    ).all()
    choices = [
        (str(account.account_id), f"{account.account_name} - {account.account_label}")
        for account in accounts
    ]
    for item in form.items:
        item.form.account.choices = choices  # type: ignore


@blueprint.route("/", methods=["GET", "POST", "DELETE"])
def index():
    form = AddLedgerEntryForm()
    _prepare_form(form)
    entries = db.session.scalars(sa.select(LedgerEntry)).all()
    return render_template("ledger/index.html", entries=entries, form=form)


# HTMX Only Views
@blueprint.route("/_/entry/item", methods=["POST"])
@htmx_only
def htmx_add_entry_item():
    form = AddLedgerEntryForm()
    form.items.append_entry()
    _prepare_form(form)
    return render_template("ledger/partials/entry-items.html", form=form)


@blueprint.route("/_/entry/item/<item_id>", methods=["DELETE"])
@htmx_only
def htmx_del_entry_item(item_id: str):
    form = AddLedgerEntryForm()
    entries = [item for item in form.items if item.id != item_id]
    while len(form.items) > 0:
        form.items.pop_entry()
    for entry in entries:
        form.items.append_entry(entry.data)
    _prepare_form(form)
    return render_template("ledger/partials/entry-items.html", form=form)


@blueprint.route("/_/entry", methods=["POST"])
@htmx_only
def htmx_add_entry():
    # TODO: Handle errors
    form = AddLedgerEntryForm()
    _prepare_form(form)
    if form.validate_on_submit():
        builder = LedgerEntryBuilder(
            dt.datetime.combine(form.date.data, dt.datetime.min.time())  # type: ignore
        )
        for item in form.items:
            account = db.session.get(LedgerAccount, item.account.data)
            if account is None:
                abort(500)
            if item.type_.data == "D":
                builder.add_debit(account, item.amount.data)
            else:
                builder.add_credit(account, item.amount.data)
        entry = builder.build()
        db.session.add(entry)
        db.session.commit()

    entries = db.session.scalars(sa.select(LedgerEntry)).all()
    return render_template("ledger/partials/ledger-entries.html", entries=entries)

app/templates/ledger/partials/entry-items.html
{% for item in form.items %}
    <tr>
        <td class="text-gray-500 font-medium text-sm whitespace-nowrap">
            {{ item.form.type_(class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset
                        ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6") }}
        </td>
        <td class="text-gray-500 font-medium text-sm whitespace-nowrap">
            {{ item.form.account(class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset
                        ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm
                        sm:leading-6") }}
        </td>
        <td class="text-gray-500 font-medium text-sm whitespace-nowrap">
            {{ item.form.amount(class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset
                        ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm
                        sm:leading-6") }}
        </td>
        <td class="text-gray-500 font-medium text-sm text-center whitespace-nowrap">
            <button hx-delete="{{ url_for('ledger.htmx_del_entry_item', item_id=item.id) }}"
                    hx-trigger="click"
                    hx-target="#entry-items"
                    hx-swap="innerHTML"
                    type="button"
                    class="text-red-600">
                <svg xmlns="http://www.w3.org/2000/svg"
                     width="24"
                     height="24"
                     viewBox="0 0 24 24"
                     fill="none"
                     stroke="currentColor"
                     stroke-width="2"
                     stroke-linecap="round"
                     stroke-linejoin="round"
                     class="lucide lucide-x">
                    <path d="M18 6 6 18" />
                    <path d="m6 6 12 12" />
                </svg>
            </button>
        </td>
    </tr>
{% endfor %}

app/templates/ledger/partials/ledger-entries.html
<table id="ledger-entries"
       class="table-auto w-full bg-white divide-y divide-gray-300">
    <thead>
        <tr>
            <th scope="col" class="font-semibold text-sm text-left pr-3 pl-4 py-3.5">Date</th>
            <th scope="col" class="font-semibold text-sm text-left pr-3 pl-4 py-3.5">Account</th>
            <th scope="col" class="font-semibold text-sm text-left pr-3 pl-4 py-3.5">Debit</th>
            <th scope="col" class="font-semibold text-sm text-left pr-3 pl-4 py-3.5">Credit</th>
        </tr>
    </thead>
    <tbody class="divide-y divide-gray-300">
        {% for entry in entries %}
            <tr>
                <td class="text-gray-900 font-medium text-sm pr-3 pl-4 py-2 whitespace-nowrap">
                    {{ entry.date.strftime("%d/%m/%Y") }}
                </td>
                <td colspan="3"
                    class="text-gray-500 font-medium text-sm text-left px-3 whitespace-nowrap">""</td>
            </tr>
            {% for item in entry.items %}
                <tr>
                    <td class="text-gray-900 font-medium text-sm pr-3 pl-4 py-2 whitespace-nowrap">-</td>
                    <td class="text-gray-500 font-medium text-sm px-3 whitespace-nowrap">
                        {{ item.account.account_name }} - {{ item.account.account_label }}
                    </td>
                    <td class="text-gray-500 font-medium text-sm px-3 whitespace-nowrap">
                        {% if item.is_debit %}
                            {{ '%0.2f'|format(item.amount|float) }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                    <td class="text-gray-500 font-medium text-sm px-3 whitespace-nowrap">
                        {% if item.is_credit %}
                            {{ '%0.2f'|format(item.amount|float) }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        {% endfor %}
    </tbody>
</table>